apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - port: 3000
      targetPort: http
      name: http
    - port: 22
      targetPort: ssh
      name: ssh
  selector:
    app: gitea
