---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
  namespace: prod
spec:
  encryptedData:
    GITEA_POSTGRES_DB: AgAwc086ljzvJNDXwHLk4CbUbZ99n8VuGJQ14HGQJSmWH5J2kPsda04Zm1MHDs/KQ6EPX3IX0QVfk5cjbWzYjVLcWgB8c1JanY3PAUBos0UvAB+AXRi1cD2nY39LLMQpoMcY4uPb39fefnqBOezd1GnmiJ75k2Q9XbHCPvYDv/QNp4PE9v5xrl3YiVbsVolUdcQjFDvJVtJKOK9q4LPI12MIPQZdLRbHrod/CJ6jVi3OpTuCjKlpXm3gVfPUU86bHbUsT0Hte02qnKadMtPSLMw+eLnGs5rgp4FNcEQwZgKneaDW+o6UBSw00z4AeGpXdu4xfoXc9ZNeb679fT0q6fbTv3QjkV8QHow86XC3PhAMmW3MykFTnZqomp+8vG/RiLXJ44eJsJidNQBGg+oJxl76cqMzHFsukk1ejMrU+mz4jG+5pKAHVU5ke15UYoBr5BfZsA0RN8V/BVR8PyUVJiCOCrHAMTcoRjDarSLLf6Er65uuI0iuYQ2qY0sxnXlN4Fsk0JQ7zEMrzpmH8LNIvNVpxF8v+Nu+cCMut9vvWCEkbydo4SKRx+JUh8RRpxkqeNjfTzxsEZ0YEDDyhgxok9xHHteYz92Nuqr7hqucFTXADL+aNBoHFm2hTkXgccKMnn7aSRIdbo8uSeIqg/POWWWo1d2uh63nnmREBW2xC6ilFanC+mOv89sOL7x0WpLz55EV32nVgs0Hmg==
    POSTGRES_PASSWORD: AgBBF2fv1DSyaq7dfsZqvubAVBzruLRTtyZ+xL99thVRXYYht7T/MJe5k4/6b40tOZ2OWFuzPVuCQTgYD1tJ4MzTjl5l/4GxZfsVUDucTCBQdmIqBgdIUmajadNtPhQLrxXVFZXGPZHPunkOaWMLmvBfkggZEI6LZa8ewhN5EEN83UjcFEJ8pvJrO//ytBXdJIyRrl7xsVvYc95iYqzaKFn92qhjQopJmQTq9LtB9bpe40JOrHcz02KXvID4GXHKK6jS3ufk1RsYW9yRqtxNbeByKuUEfjbypHzkDXjWQvCkD2e1nyKUliS9qxxJ4eOKzneWqiNXoSWBM2QO9gRuYT2SDX9lhl06Ibn/hVlX5w/7l8trb+U2uiQNnrDSOrqRKhR20qMMF/YhRuz+K+wi4Xk8+GGuQsEL0qz14SYCijAEADcaBkflgYRGTuh368Q5eki8ZervNhkhaR7k/rtnIPsAVn+H+d5VipsQjf4qutBUi/A0ikNaF8sEVWYUTmf2azjrXPuve2h06PZAAB4R0lvJthoguKWoa8atgtFAcJ25uXk+SIXs+Iwenj1xxMADcU7S1sEWGnY7Z362cKLtpP3a2XvCQbh6hFfDle1K7akCilwFLo9e6NND+AFkltigRPnXujG9P4x8VR5ojK+6eirKtCtM7buJICyN1X91PlBkNFwZfl1GkRWOhDUYjnjgiSPna82UekfihIUPxNL6cWSgSQ==
    POSTGRES_USER: AgCWK4PH42xDivHbP0Arj0lMgUiIIn8jXXnQW3u7vKf/Z/udVllP8iK5DzlJ6mz6UzUCrxftn7lY+SC+U21RNR/V/ACv8CazLlHuo+j+SG5/yuh3NplHJb5XWfbVQW3qAKJMw3ZvVr53CihTaNn4Fs3xlMFRdzymjGowHXhAQ6rFq+Z1rBZmupBM8Xy9qmY1g2Frk6P+jatM30mVuFoIAzWO875P5Hsqso/b+FY3sbx4lvfo7FPCOwkCHN0DUFDJtg+UDi2bAMXH3rj31CrrcvGTj/kchBs0loNn3TbohEiTgYa1Y0jzXkIV13SCCbD5DFO6QidP//GVSNDIELDwPmQInpzl6EcgeFAE3CC28/kGk9kG2eXotN1aiVcY0lR487m5+Uhkg11d8FAkGB+B0XKw0S60c8w3ugo+wqOIWwxgu8majZqDtvnbWUjEWmH7h7h697QlviKsoDGg9ZAw7xWeECp9B9M03hvFKRniD8/d+DmRk8B+6XS8Eqj+CQyq3YAohrL1BpAhMnJYbLiNqAAvAvloBELzq6ejlBumV18drvW8BfjDuKvzbyDHr+msC7GGQ4I/IeamYvANg8wFqfuirzN17qMs2GDWrjELBBK2t9hmCmewYMghVexmu+cRo9LF8Ic5GP0T4jtXXj/+3uoHHhkr2I7XlXIP0MPWmIi8TIGuJkLhDC18/6cOLgl7yCrPZGmfBgBSb/1Fp2t7RFpXcaE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
      namespace: prod
    type: Opaque
