apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../../../base
  - namespace.yaml
  - local-storage.yaml
  - sealed-secrets/postgres-secret.yaml

patches:
  - target:
      kind: Deployment
      name: gitea
    path: node-selector.yaml
  - target:
      kind: Deployment
      name: postgres
    path: node-selector.yaml
  - path: service-nodeport.yaml
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-storage
      - op: add
        path: /spec/volumeName
        value: postgres-pv
  - target:
      kind: PersistentVolumeClaim
      name: gitea-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-storage
      - op: add
        path: /spec/volumeName
        value: gitea-pv
