apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  $patch: replace
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30180
    - name: ssh
      port: 22
      targetPort: ssh
      nodePort: 30122
  selector:
    app: gitea